node {
      stage('SCM') {
        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/master']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'SparseCheckoutPaths',
                     sparseCheckoutPaths: [[path: 'inventory-service']]
            ]],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'https://github.com/sivaprasadreddy/geeknight-cloud-native-apps-springcloud.git']]
        ])
      }

      stage('Build'){
        sh 'cd inventory-service && ./mvnw clean package'
      }

}